package sql.model;
// Generated 15 janv. 2014 17:39:49 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facture generated by hbm2java
 */
public class Facture  implements java.io.Serializable {


     private Integer idFacture;
     private User user;
     private int nbrLigne;
     private float montantTotal;
     private Date dateValid;
     private Set ligneFactures = new HashSet(0);

    public Facture() {
    }

	
    public Facture(User user, int nbrLigne, float montantTotal, Date dateValid) {
        this.user = user;
        this.nbrLigne = nbrLigne;
        this.montantTotal = montantTotal;
        this.dateValid = dateValid;
    }
    public Facture(User user, int nbrLigne, float montantTotal, Date dateValid, Set ligneFactures) {
       this.user = user;
       this.nbrLigne = nbrLigne;
       this.montantTotal = montantTotal;
       this.dateValid = dateValid;
       this.ligneFactures = ligneFactures;
    }
   
    public Integer getIdFacture() {
        return this.idFacture;
    }
    
    public void setIdFacture(Integer idFacture) {
        this.idFacture = idFacture;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getNbrLigne() {
        return this.nbrLigne;
    }
    
    public void setNbrLigne(int nbrLigne) {
        this.nbrLigne = nbrLigne;
    }
    public float getMontantTotal() {
        return this.montantTotal;
    }
    
    public void setMontantTotal(float montantTotal) {
        this.montantTotal = montantTotal;
    }
    public Date getDateValid() {
        return this.dateValid;
    }
    
    public void setDateValid(Date dateValid) {
        this.dateValid = dateValid;
    }
    public Set getLigneFactures() {
        return this.ligneFactures;
    }
    
    public void setLigneFactures(Set ligneFactures) {
        this.ligneFactures = ligneFactures;
    }




}


