package sql.model;
// Generated 15 janv. 2014 17:39:49 by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Fournisseur generated by hbm2java
 */
public class Fournisseur implements java.io.Serializable {

    private Short idFournisseur;
    private String nomFournisseur;
    private String tel;
    private String adr;
    private String mail;
    private Set articles = new HashSet(0);

    public Fournisseur() {
    }

    public Fournisseur(String nomFournisseur) {
        this.nomFournisseur = nomFournisseur;
    }

    public Fournisseur(String nomFournisseur, String tel, String adr, String mail, Set articles) {
        this.nomFournisseur = nomFournisseur;
        this.tel = tel;
        this.adr = adr;
        this.mail = mail;
        this.articles = articles;
    }

    public Short getIdFournisseur() {
        return this.idFournisseur;
    }

    public void setIdFournisseur(Short idFournisseur) {
        this.idFournisseur = idFournisseur;
    }

    public String getNomFournisseur() {
        return this.nomFournisseur;
    }

    public void setNomFournisseur(String nomFournisseur) {
        this.nomFournisseur = nomFournisseur;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getAdr() {
        return this.adr;
    }

    public void setAdr(String adr) {
        this.adr = adr;
    }

    public String getMail() {
        return this.mail;
    }

    public void setMail(String mail) {
        this.mail = mail;
    }

    public Set getArticles() {
        return this.articles;
    }

    public void setArticles(Set articles) {
        this.articles = articles;
    }

    @Override
    public String toString() {
        return nomFournisseur;
    }
}
