package sql.model;
// Generated 15 janv. 2014 17:39:49 by Hibernate Tools 3.2.1.GA



/**
 * LigneFacture generated by hbm2java
 */
public class LigneFacture  implements java.io.Serializable {


     private LigneFactureId id;
     private Article article;
     private Facture facture;
     private int qteArticle;
     private float subtotal;

    public LigneFacture() {
    }

    public LigneFacture(LigneFactureId id, Article article, Facture facture, int qteArticle, float subtotal) {
       this.id = id;
       this.article = article;
       this.facture = facture;
       this.qteArticle = qteArticle;
       this.subtotal = subtotal;
    }
   
    public LigneFactureId getId() {
        return this.id;
    }
    
    public void setId(LigneFactureId id) {
        this.id = id;
    }
    public Article getArticle() {
        return this.article;
    }
    
    public void setArticle(Article article) {
        this.article = article;
    }
    public Facture getFacture() {
        return this.facture;
    }
    
    public void setFacture(Facture facture) {
        this.facture = facture;
    }
    public int getQteArticle() {
        return this.qteArticle;
    }
    
    public void setQteArticle(int qteArticle) {
        this.qteArticle = qteArticle;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = this.qteArticle*this.article.getPVente();
    }

    @Override
    public String toString() {
        return "LigneFacture{" + "id=" + id + ", article=" + article + ", facture=" + facture + ", qteArticle=" + qteArticle + ", subtotal=" + subtotal + '}';
    }

}


