package sql.model;
// Generated 15 janv. 2014 17:39:49 by Hibernate Tools 3.2.1.GA

/**
 * LigneFactureId generated by hbm2java
 */
public class LigneFactureId implements java.io.Serializable {

    private int idFacture;
    private int idArticle;

    public LigneFactureId() {
    }

    public LigneFactureId(int idFacture, int idArticle) {
        this.idFacture = idFacture;
        this.idArticle = idArticle;
    }

    public int getIdFacture() {
        return this.idFacture;
    }

    public void setIdFacture(int idFacture) {
        this.idFacture = idFacture;
    }

    public int getIdArticle() {
        return this.idArticle;
    }

    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }

    @Override
    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof LigneFactureId)) {
            return false;
        }
        LigneFactureId castOther = (LigneFactureId) other;

        return (this.getIdFacture() == castOther.getIdFacture())
                && (this.getIdArticle() == castOther.getIdArticle());
    }

    /**
     *
     * @return
     */
    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getIdFacture();
        result = 37 * result + this.getIdArticle();
        return result;
    }

    @Override
    public String toString() {
        return "{idFacture=" + idFacture + ", idArticle=" + idArticle + '}';
    }
    
}
