package sql.model;
// Generated 15 janv. 2014 17:39:49 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Short id;
     private String userName;
     private String psswd;
     private Boolean isAdmin;
     private String FName;
     private String LName;
     private Set factures = new HashSet(0);

    public User() {
    }

	
    public User(String userName, String psswd) {
        this.userName = userName;
        this.psswd = psswd;
    }
    public User(String userName, String psswd, Boolean isAdmin, String FName, String LName, Set factures) {
       this.userName = userName;
       this.psswd = psswd;
       this.isAdmin = isAdmin;
       this.FName = FName;
       this.LName = LName;
       this.factures = factures;
    }
   
    public Short getId() {
        return this.id;
    }
    
    public void setId(Short id) {
        this.id = id;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPsswd() {
        return this.psswd;
    }
    
    public void setPsswd(String psswd) {
        this.psswd = psswd;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public String getFName() {
        return this.FName;
    }
    
    public void setFName(String FName) {
        this.FName = FName;
    }
    public String getLName() {
        return this.LName;
    }
    
    public void setLName(String LName) {
        this.LName = LName;
    }
    public Set getFactures() {
        return this.factures;
    }
    
    public void setFactures(Set factures) {
        this.factures = factures;
    }




}


