/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gestion.ui;

import sql.model.VousEtesCo;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Container;
import java.awt.GridBagConstraints;
import java.awt.Image;
import java.awt.Insets;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ali
 */

public class GestionFrame extends javax.swing.JFrame {

    private String LogoLocation = "src\\assets\\LogoTitle\\logo.png";
    private String MyTitle = "LeaderPapetrie - Gestion";
    private Image backgroundImage;
    

    /**
     * Creates new form GetsionFrame
     */
    public GestionFrame() throws IOException {
        GridBagConstraints c = new GridBagConstraints();
//        initComponents();
        backgroundImage = ImageIO.read(new File(LogoLocation));
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(MyTitle);
        setIconImage(backgroundImage);
        this.setVisible(true);
        this.setSize(1100, 601);
        this.setLocationRelativeTo(null);
        setResizable(false);
        this.setLayout(new BorderLayout());
        this.add("North", new TitlePanel());
        this.add("Center", new tabed());
        this.add("South", new VousEtesCo());       
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Vous êtes connectés en tant que :              ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(900, 900, 900)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(570, 570, 570)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void ajoutComposant(Container conteneur, Component composant,
            int gridx, int gridy, int gridwidth, int gridheight, int weightx, int weighty, int fill, int anchor) {
        GridBagConstraints contrainte = new GridBagConstraints();
        contrainte.gridx = gridx;
        contrainte.gridy = gridy;
        contrainte.gridwidth = gridwidth;
        contrainte.gridheight = gridheight;
        contrainte.weightx = weighty;
        contrainte.gridy = gridy;
        contrainte.fill = fill;
        contrainte.anchor = anchor;
        conteneur.add(composant,contrainte);
    }
    
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel("com.jgoodies.looks.windows.WindowsLookAndFeel");
            UIManager.getDefaults().put("TabbedPane.contentBorderInsets", new Insets(0, 0, 0, 0));
            UIManager.getDefaults().put("TabbedPane.tabsOverlapBorder", true);
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException e) {
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GestionFrame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GestionFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
